pipeline {
    agent any
    stages {
        stage('provision infrastructure') {
         
            steps {
                script {
                    dir('./FrontendTF/terraform') {
                    withAWS(region:"ap-southeast-2", credentials:"# to add"){
                        sh "terraform init -reconfigure"
                        sh "terraform apply --auto-approve"
                        
                        }
                    }
                }
        
           }
        }

    }
}